# action.yml
name: 'Copilot deploy'
description: 'Copilot deploy'
author: Federico Rapetti
branding:
  icon: 'arrow-up-circle'
  color: 'orange'
inputs:
  environments:
    description: 'Environments to deploy'
    required: true
  workloads:
    description: 'Workloads to deploy'
    required: true
  bucket:
    description: 'Bucket to upload CloudFormation template'
    required: false
  deploy_method:
    description: 'Set the deploy method (manual | automatic)'
    required: false
    default: manual
runs:
  using: 'docker'
  image: 'Dockerfile'